services:
  spring:
    environment:
      SPRING_PROFILES_ACTIVE: loadtest
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-chalkak}
      DB_USERNAME: ${POSTGRES_USER:-chalkak}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-chalkak}
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: chalkak-application
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    volumes:
      - ./monitoring/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar
    container_name: chalkak-application
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: chalkak-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
  grafana:
    image: grafana/grafana:13.2.1
    container_name: chalkak-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - prometheus
  tempo:
    image: grafana/tempo:2.10.8
    container_name: chalkak-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./monitoring/tempo.yaml:/etc/tempo.yaml
    restart: always
  k6:
    image: grafana/k6:2.2.0
    container_name: chalkak-k6
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    volumes:
      - ./monitoring/k6/script.js:/script.js
    entrypoint: ["sh", "-c"]
    command: ["sleep 5 && k6 run /script.js"]
    network_mode: host
  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter:v0.20.1
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER:-chalkak}:${POSTGRES_PASSWORD:-chalkak}@postgres:5432/${POSTGRES_DB:-chalkak}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  grafana-data:
